language: node_js
node_js:
- '9'
- '8'
cache:
  directories:
  - node_modules
notifications:
  email: false
install:
- yarn
script:
- yarn test
- yarn build
after_success:
  - npm run travis-deploy-once "npm run semantic-release"
branches:
  only:
    - master
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GH_TOKEN
  local-dir: dist
  on:
    branch: master
    condition: $TRAVIS_NODE_VERSION = "9"